import streamlit as st
from groq import Groq

from fpdf import FPDF

def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "AI Product Insight Report", ln=True)

    pdf.ln(5)

    # Subtitle
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 8, "Generated by AI Product Insight Tool", ln=True)

    pdf.ln(10)

from datetime import datetime

pdf.set_font("Arial", size=9)
pdf.cell(0, 8, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
pdf.ln(5)

    # Body
    pdf.set_font("Arial", size=12)

    for line in text.split("\n"):
        line = line.strip()

        # Detect section headers
        if line.lower().startswith("1.") or "complaint" in line.lower():
            pdf.ln(5)
            pdf.set_font("Arial", "B", 13)
            pdf.cell(0, 8, line, ln=True)
            pdf.set_font("Arial", size=12)

        elif line.lower().startswith("2.") or "positive" in line.lower():
            pdf.ln(5)
            pdf.set_font("Arial", "B", 13)
            pdf.cell(0, 8, line, ln=True)
            pdf.set_font("Arial", size=12)

        elif line.lower().startswith("3.") or "improvement" in line.lower():
            pdf.ln(5)
            pdf.set_font("Arial", "B", 13)
            pdf.cell(0, 8, line, ln=True)
            pdf.set_font("Arial", size=12)

        else:
            pdf.multi_cell(0, 8, line)

    return pdf.output(dest="S").encode("latin-1")

import os
client = Groq(api_key=os.environ["GROQ_API_KEY"])

st.title("AI Product Insight Tool")

st.write("Enter customer reviews and get AI-powered insights.")

reviews = st.text_area("Paste reviews (one per line):")

if st.button("Analyze Feedback"):

    if not reviews.strip():
        st.warning("Please enter some reviews first.")
    else:
        with st.spinner("Analyzing feedback..."):

            response = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[
                    {
                        "role": "user",
                        "content": f"""
You are a product analyst.

Analyze these customer reviews:

{reviews}

Return:
1. Top complaints
2. Top positives
3. 3 product improvement ideas
"""
                    }
                ]
            )

            analysis_text = response.choices[0].message.content

        st.subheader("📊 AI Analysis")
        st.markdown(analysis_text)

        pdf = create_pdf(analysis_text)

        st.download_button(
            label="📥 Download Report as PDF",
            data=pdf,
            file_name="ai_product_report.pdf",
            mime="application/pdf"
        )
